# Generated by Django 4.2.8 on 2025-11-07 10:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucDichVu',
            fields=[
                ('MaDanhMuc', models.CharField(help_text='Mã định danh duy nhất cho từng danh mục dịch vụ Spa (VD: DM001, DM002, ...)', max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(5)])),
                ('TenDanhMuc', models.CharField(help_text="Tên danh mục dịch vụ (VD: 'Chăm sóc da mặt', 'Massage thư giãn')", max_length=200)),
                ('MoTa', models.TextField(blank=True, help_text='Mô tả chi tiết về nhóm dịch vụ (VD: các loại liệu trình trong danh mục)', null=True)),
            ],
            options={
                'verbose_name': 'Danh Mục Dịch Vụ',
                'verbose_name_plural': 'Danh Mục Dịch Vụ',
                'db_table': 'DanhMucDichVu',
            },
        ),
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('MaDichVu', models.CharField(help_text='Mã định danh duy nhất cho từng dịch vụ (VD: DV001, DV002, ...)', max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(5)])),
                ('TenDichVu', models.CharField(help_text="Tên dịch vụ Spa (VD: 'Massage đá nóng', 'Trị mụn chuyên sâu')", max_length=200)),
                ('MoTa', models.TextField(help_text='Mô tả nội dung, liệu trình, sản phẩm sử dụng, giá và thời gian dịch vụ')),
                ('TrangThaiHienThi', models.BooleanField(default=True, help_text='Trạng thái hiển thị dịch vụ (1 = đang kinh doanh, 0 = tạm ẩn)')),
                ('MaDanhMuc', models.ForeignKey(db_column='MaDanhMuc', help_text='Khóa ngoại liên kết đến bảng DanhMucDichVu (MaDanhMuc)', on_delete=django.db.models.deletion.CASCADE, to='aurora.danhmucdichvu')),
            ],
            options={
                'verbose_name': 'Dịch Vụ',
                'verbose_name_plural': 'Dịch Vụ',
                'db_table': 'DichVu',
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKhachHang', models.CharField(blank=True, help_text='VD: KH001', max_length=5, primary_key=True, serialize=False)),
                ('SDT', models.CharField(max_length=10)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Khách Hàng',
                'verbose_name_plural': 'Khách Hàng',
                'db_table': 'KhachHang',
            },
        ),
        migrations.CreateModel(
            name='QuyDoiDiem',
            fields=[
                ('MaQuyDoi', models.CharField(help_text='Mã quy đổi', max_length=5, primary_key=True, serialize=False)),
                ('GiaTriDiem', models.IntegerField(help_text='Giá trị điểm (số điểm cần để quy đổi)')),
                ('GiaTriQuyDoi', models.DecimalField(decimal_places=2, help_text='Giá trị quy đổi tương ứng (VNĐ)', max_digits=10)),
            ],
            options={
                'verbose_name': 'Quy Đổi Điểm',
                'verbose_name_plural': 'Quy Đổi Điểm',
                'db_table': 'QuyDoiDiem',
            },
        ),
        migrations.CreateModel(
            name='DiemTichLuy',
            fields=[
                ('MaKhachHang', models.OneToOneField(db_column='MaKhachHang', help_text='Mã khách hàng (VD: KH001, KH002, ...)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aurora.khachhang', validators=[django.core.validators.MinLengthValidator(5)])),
                ('SoDiemHienTai', models.IntegerField(default=0, help_text='Số điểm tích lũy hiện tại của khách hàng')),
            ],
            options={
                'verbose_name': 'Điểm Tích Lũy',
                'verbose_name_plural': 'Điểm Tích Lũy',
                'db_table': 'DiemTichLuy',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNhanVien', models.CharField(blank=True, max_length=5, primary_key=True, serialize=False)),
                ('ChucVu', models.CharField(max_length=100)),
                ('NgayVaoLam', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhân Viên',
                'verbose_name_plural': 'Nhân Viên',
                'db_table': 'NhanVien',
            },
        ),
        migrations.CreateModel(
            name='LichSuTichDiem',
            fields=[
                ('MaGiaoDich', models.CharField(help_text='Mã giao dịch', max_length=5, primary_key=True, serialize=False)),
                ('LoaiGiaoDich', models.CharField(choices=[('Tích điểm', 'Tích điểm'), ('Quy đổi điểm', 'Quy đổi điểm')], help_text='Loại giao dịch', max_length=50)),
                ('ChiTietGiaoDich', models.CharField(help_text='Chi tiết giao dịch', max_length=300)),
                ('NgayGiaoDich', models.DateTimeField(auto_now_add=True, help_text='Ngày giao dịch')),
                ('SoDiemThayDoi', models.IntegerField(help_text='Số điểm thay đổi (+ hoặc -)')),
                ('MaKhachHang', models.ForeignKey(help_text='Khách hàng thực hiện giao dịch', on_delete=django.db.models.deletion.CASCADE, to='aurora.khachhang')),
                ('MaQuyDoi', models.ForeignKey(blank=True, help_text='Chính sách quy đổi được áp dụng (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aurora.quydoidiem')),
            ],
            options={
                'verbose_name': 'Lịch Sử Tích Điểm',
                'verbose_name_plural': 'Lịch Sử Tích Điểm',
                'db_table': 'LichSuTichDiem',
            },
        ),
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('MaLichHen', models.CharField(help_text='Mã định danh duy nhất cho từng lịch hẹn (LH001, LH002,...)', max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(5)])),
                ('NgayDatLich', models.DateTimeField(help_text='Ngày và giờ khách thực hiện đặt lịch')),
                ('NgayHen', models.DateTimeField(help_text='Ngày và giờ hẹn thực tế để thực hiện dịch vụ')),
                ('TrangThai', models.CharField(choices=[('Đang chờ', 'Đang chờ'), ('Đang thực hiện', 'Đang thực hiện'), ('Hoàn thành', 'Hoàn thành'), ('Đã hủy', 'Đã hủy')], help_text='Mô tả trạng thái hiện tại của lịch hẹn', max_length=25)),
                ('MaDichVu', models.ForeignKey(db_column='MaDichVu', on_delete=django.db.models.deletion.CASCADE, to='aurora.dichvu')),
                ('MaKhachHang', models.ForeignKey(db_column='MaKhachHang', help_text='Mã duy nhất đại diện cho mỗi khách hàng', on_delete=django.db.models.deletion.CASCADE, to='aurora.khachhang')),
                ('MaNhanVien', models.ForeignKey(db_column='MaNhanVien', on_delete=django.db.models.deletion.CASCADE, to='aurora.nhanvien')),
            ],
            options={
                'verbose_name': 'Lịch Hẹn',
                'verbose_name_plural': 'Lịch Hẹn',
                'db_table': 'LichHen',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('MaCauHoi', models.CharField(help_text='Mã câu hỏi', max_length=5, primary_key=True, serialize=False)),
                ('CauHoi', models.CharField(help_text='Cau Hoi', max_length=300)),
                ('CauTraLoi', models.TextField(help_text='Câu trả lời')),
                ('NgayCapNhat', models.DateTimeField(auto_now_add=True, help_text='Ngày cập nhật gần nhất')),
                ('TrangThaiHienThi', models.BooleanField(default=True, help_text='Trạng thái hiển thị')),
                ('MaNhanVien', models.ForeignKey(help_text='Mã nhân viên', on_delete=django.db.models.deletion.CASCADE, to='aurora.nhanvien')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'db_table': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('MaBaiViet', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('TieuDeBaiViet', models.CharField(max_length=200)),
                ('NoiDungBaiViet', models.TextField()),
                ('NgayDang', models.DateTimeField()),
                ('TrangThaiHienThi', models.BooleanField(default=True)),
                ('MaNhanVien', models.ForeignKey(db_column='MaNhanVien', help_text='Nhân viên đăng bài viết', on_delete=django.db.models.deletion.CASCADE, to='aurora.nhanvien')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
                'db_table': 'Blog',
            },
        ),
        migrations.AddConstraint(
            model_name='lichhen',
            constraint=models.CheckConstraint(check=models.Q(('TrangThai__in', ['Đang chờ', 'Đang thực hiện', 'Hoàn thành', 'Đã hủy'])), name='chk_trangthai_lichhen'),
        ),
    ]
