# Generated by Django 4.2.8 on 2025-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='HinhAnh',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
