# Generated by Django 4.2.8 on 2025-11-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0002_blog_hinhanh'),
    ]

    operations = [
        migrations.AddField(
            model_name='dichvu',
            name='HinhAnh',
            field=models.ImageField(blank=True, null=True, upload_to='dichvu/'),
        ),
    ]
