# Generated by Django 4.2.8 on 2025-11-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0003_dichvu_hinhanh'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='DiaChi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='HoTen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='NgaySinh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
