# Generated by Django 4.2.8 on 2025-11-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0004_khachhang_diachi_khachhang_hoten_khachhang_ngaysinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='DiaChi',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='HoTen',
            field=models.CharField(max_length=200),
        ),
    ]
