# Generated by Django 4.2.8 on 2025-11-11 10:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0005_alter_khachhang_diachi_alter_khachhang_hoten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='NoiDungBaiViet',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
