# Generated by Django 4.2.8 on 2025-11-12 05:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0006_alter_blog_noidungbaiviet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dichvu',
            name='MoTa',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
