# Generated by Django 4.2.8 on 2025-11-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0007_alter_dichvu_mota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lichsutichdiem',
            options={},
        ),
        migrations.AlterModelTable(
            name='lichsutichdiem',
            table=None,
        ),
    ]
