# Generated by Django 4.2.8 on 2025-11-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0008_alter_lichsutichdiem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lichsutichdiem',
            options={'verbose_name': 'Lịch Sử Tích Điểm', 'verbose_name_plural': 'Lịch Sử Tích Điểm'},
        ),
        migrations.AlterModelTable(
            name='lichsutichdiem',
            table='LichSuTichDiem',
        ),
    ]
