# Generated by Django 4.2.8 on 2025-11-13 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0009_alter_lichsutichdiem_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lichhen',
            name='chk_trangthai_lichhen',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='MaDichVu',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='MaKhachHang',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='MaNhanVien',
        ),
        migrations.RemoveField(
            model_name='lichhen',
            name='NgayDatLich',
        ),
        migrations.AddField(
            model_name='lichhen',
            name='DanhMucDichVu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aurora.danhmucdichvu'),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='DichVu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lichhen_dichvu', to='aurora.dichvu'),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='DienThoai',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='SĐT di động'),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='HoTen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ và tên'),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='KhungGio',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Khung giờ'),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='MaGiamGia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã giảm giá'),
        ),
        migrations.AlterField(
            model_name='lichhen',
            name='NgayHen',
            field=models.DateField(verbose_name='Ngày đặt'),
        ),
        migrations.AlterField(
            model_name='lichhen',
            name='TrangThai',
            field=models.CharField(choices=[('Đang chờ', 'Đang chờ'), ('Đang thực hiện', 'Đang thực hiện'), ('Hoàn thành', 'Hoàn thành'), ('Đã hủy', 'Đã hủy')], default='Đang chờ', max_length=25, verbose_name='Trạng thái'),
        ),
    ]
