# Generated by Django 4.2.8 on 2025-11-13 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aurora', '0010_remove_lichhen_chk_trangthai_lichhen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhen',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KhachHang_LichHen', to=settings.AUTH_USER_MODEL),
        ),
    ]
