# Generated by Django 4.2.8 on 2025-11-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0011_lichhen_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='VaiTro',
            field=models.CharField(choices=[('MANAGER', 'Quản lý'), ('CONTENT', 'Nhân viên nội dung'), ('RECEPTION', 'Nhân viên lễ tân')], default='RECEPTION', max_length=20),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
