# Generated by Django 4.2.8 on 2025-11-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0012_nhanvien_vaitro_nhanvien_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='dichvu',
            name='GiaTien',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Giá tiền dịch vụ (VNĐ)', max_digits=12),
        ),
    ]
