# Generated by Django 4.2.8 on 2025-11-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0013_dichvu_giatien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanvien',
            name='ChucVu',
        ),
        migrations.AddField(
            model_name='blog',
            name='NgayCapNhat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='NgayDang',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='NgayCapNhat',
            field=models.DateTimeField(auto_now=True, help_text='Ngày cập nhật gần nhất'),
        ),
    ]
