# Generated by Django 4.2.8 on 2025-11-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0014_remove_nhanvien_chucvu_blog_ngaycapnhat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsutichdiem',
            name='NgayGiaoDich',
            field=models.DateTimeField(auto_now=True, help_text='Ngày giao dịch'),
        ),
    ]
