# Generated by Django 4.2.8 on 2025-11-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0015_alter_lichsutichdiem_ngaygiaodich'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsutichdiem',
            name='NgayCapNhat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lichsutichdiem',
            name='NgayGiaoDich',
            field=models.DateTimeField(auto_now_add=True, help_text='Ngày giao dịch'),
        ),
    ]
