# Generated by Django 4.2.8 on 2025-11-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0016_lichsutichdiem_ngaycapnhat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichhen',
            name='KhungGio',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Khung giờ'),
        ),
    ]
