# Generated by Django 4.2.8 on 2025-11-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0017_alter_lichhen_khunggio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='VaiTro',
            field=models.CharField(choices=[('MANAGER', 'Quản lý'), ('CONTENT', 'Nhân viên nội dung'), ('RECEPTION', 'Nhân viên lễ tân'), ('STAFF', 'Chuyên viên')], default='RECEPTION', max_length=20),
        ),
    ]
