# Generated by Django 4.2.8 on 2025-11-25 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0018_alter_nhanvien_vaitro'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsutichdiem',
            name='HanhDong',
            field=models.CharField(blank=True, choices=[('+', 'Tăng'), ('-', 'Giảm')], help_text='Giao dịch là cộng hay trừ điểm', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lichsutichdiem',
            name='NguoiThucHien',
            field=models.ForeignKey(blank=True, help_text='Nhân viên thực hiện giao dịch (tăng/giảm điểm)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aurora.nhanvien'),
        ),
    ]
