# Generated by Django 4.2.8 on 2025-11-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0019_lichsutichdiem_hanhdong_lichsutichdiem_nguoithuchien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichhen',
            name='KhungGio',
            field=models.CharField(blank=True, choices=[('09:00 - 10:30', '09:00 - 10:30'), ('10:30 - 12:00', '10:30 - 12:00'), ('13:30 - 15:00', '13:30 - 15:00'), ('15:00 - 16:30', '15:00 - 16:30'), ('16:30 - 18:00', '16:30 - 18:00'), ('18:00 - 19:30', '18:00 - 19:30'), ('19:30 - 21:00', '19:30 - 21:00')], max_length=30, null=True),
        ),
    ]
