# Generated by Django 4.2.8 on 2025-11-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0020_alter_lichhen_khunggio'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='NhomChuyenVien',
            field=models.CharField(blank=True, choices=[('DA_MAT', 'Chăm sóc da mặt'), ('MASSAGE', 'Massage thư giãn'), ('NAIL', 'Chăm sóc tay và chân'), ('TOAN_THAN', 'Liệu trình làm đẹp toàn thân')], help_text='Nhóm chuyên môn của chuyên viên', max_length=20, null=True),
        ),
    ]
