# Generated by Django 4.2.8 on 2025-11-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0021_nhanvien_nhomchuyenvien'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhen',
            name='NhanVienThucHien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lichhen_thuchien', to='aurora.nhanvien', verbose_name='Nhân viên thực hiện'),
        ),
    ]
