# Generated by Django 4.2.8 on 2025-11-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0022_lichhen_nhanvienthuchien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichsutichdiem',
            name='MaQuyDoi',
        ),
        migrations.DeleteModel(
            name='QuyDoiDiem',
        ),
    ]
