# Generated by Django 4.2.8 on 2025-12-03 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0023_remove_lichsutichdiem_maquydoi_delete_quydoidiem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucFAQ',
            fields=[
                ('MaDanhMuc', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('TenDanhMuc', models.CharField(max_length=200, unique=True)),
                ('MoTaDanhMuc', models.TextField(blank=True, null=True)),
                ('TrangThaiHienThi', models.BooleanField(default=True)),
                ('NgayCapNhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Danh mục FAQ',
                'db_table': 'DanhMucFAQ',
                'ordering': ['MaDanhMuc'],
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-MaCauHoi'], 'verbose_name': 'Câu hỏi thường gặp', 'verbose_name_plural': 'Câu hỏi thường gặp'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='CauHoi',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='faq',
            name='CauTraLoi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='MaCauHoi',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='NgayCapNhat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='TrangThaiHienThi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='MaDanhMuc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_list', to='aurora.danhmucfaq'),
        ),
    ]
