# Generated by Django 5.2.7 on 2025-12-06 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0024_danhmucfaq_alter_faq_options_alter_faq_cauhoi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhungGio',
            fields=[
                ('MaKhungGio', models.CharField(help_text='Mã định danh duy nhất cho khung giờ (VD: KG001, KG002, ...)', max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(5)])),
                ('GioBatDau', models.TimeField(help_text='Giờ bắt đầu khung giờ (HH:MM:SS)')),
                ('GioKetThuc', models.TimeField(help_text='Giờ kết thúc khung giờ (HH:MM:SS)')),
            ],
            options={
                'db_table': 'KhungGio',
                'ordering': ['GioBatDau'],
            },
        ),
        migrations.AddField(
            model_name='lichhen',
            name='LyDo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý Do'),
        ),
    ]
