# Generated by Django 5.2.7 on 2025-12-06 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0025_khunggio_lichhen_lydo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichhen',
            name='KhungGio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lichhen_khunggio', to='aurora.khunggio'),
        ),
    ]
