# Generated by Django 4.2.8 on 2025-11-15 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aurora', '0013_dichvu_giatien'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhatKyHoatDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanh_dong', models.CharField(max_length=255)),
                ('doi_tuong', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('mo_ta', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('thoi_gian', models.DateTimeField(default=django.utils.timezone.now)),
                ('nhan_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_logs', to='aurora.nhanvien')),
            ],
            options={
                'db_table': 'StaffActivityLog',
                'ordering': ['-thoi_gian'],
            },
        ),
    ]
